# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
# avoid duplicate tests in PRs
branches:
  only:
    - master
julia:
  - 1.3
matrix:
  allow_failures:
    - julia: nightly
#env:
#  - GROUP=Core
#  - GROUP=Min
#  - GROUP=EquibrilateI
#  - GROUP=EquibrilateII
#  - GROUP=Misc
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Catalyst"); Pkg.test("Catalyst"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("Catalyst")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("Catalyst")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
