# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
# avoid duplicate tests in PRs
branches:
  only:
    - master
julia:
  - 1
matrix:
  allow_failures:
    - julia: nightly
#env:
#  - GROUP=Core
#  - GROUP=Min
#  - GROUP=EquibrilateI
#  - GROUP=EquibrilateII
#  - GROUP=Misc
notifications:
  email: false
script: julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=false)'

coveralls: false
codecov: false
